#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if [ -f "$DIR/node" ]; then
  NODE_EXE="$DIR/node"
else
  NODE_EXE="node"
fi
exec "$NODE_EXE" "$DIR/dist/cli/cli-entry.js" "$@"
